import { LitElement, css, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';

import './components/activity-item';
import './components/standup-card';

import { gitActivityToActivities } from './services/git-to-activity';
import { MockStandupAgent } from './services/standup-agent';

import type { Activity, GitActivity, Standup } from './types';

/**
 * Main Daily Diff application component.
 *
 * Activity now comes from REAL local Git data:
 *
 *   GET /api/git-activity  →  GitActivity
 *   gitActivityToActivities()  →  Activity[]
 *   <activity-item> renders each Activity
 *
 * The raw GitActivity is also kept so the debug
 * panel below can show the untransformed data.
 */
@customElement('daily-diff-app')
export class DailyDiffApp extends LitElement {
  /**
   * Real Git activity returned from:
   *
   * GET /api/git-activity
   *
   * Because this property uses @state(), Lit will automatically
   * update the component when the value changes.
   */
  @state()
  private gitActivity?: GitActivity;

  /**
   * Stores an error message if Git activity cannot be loaded.
   *
   * Again, @state() means changing this value causes Lit
   * to update the UI.
   */
  @state()
  private gitError?: string;

  /**
   * Activity displayed by our existing <activity-item> components.
   *
   * Starts empty — the fetch is asynchronous, so we
   * populate it once /api/git-activity responds and
   * gitActivityToActivities() has transformed the data.
   */
  @state()
  private activity: Activity[] = [];

  /**
   * The standup generated by our agent.
   *
   * It starts as undefined because we haven't generated
   * a standup yet.
   */
  @state()
  private standup?: Standup;

  /**
   * Our current fake standup agent.
   *
   * Eventually this can be replaced by the real AI/A2UI
   * implementation.
   */
  private agent = new MockStandupAgent();

  /**
   * Lit lifecycle method.
   *
   * connectedCallback() runs when <daily-diff-app>
   * is attached to the DOM.
   *
   * We call super.connectedCallback() because LitElement
   * has its own setup work that must happen here.
   *
   * Then we load the local Git activity.
   */
  connectedCallback() {
    super.connectedCallback();

    void this.loadGitActivity();
  }

  /**
   * Ask our local Vite server for Git activity.
   *
   * Remember the flow:
   *
   * Browser
   *   ↓
   * GET /api/git-activity
   *   ↓
   * Vite plugin (Node)
   *   ↓
   * collectGitActivity()
   *   ↓
   * Git
   */
  private async loadGitActivity() {
    try {
      const response = await fetch('/api/git-activity');

      /**
       * fetch() does NOT throw an error for HTTP errors
       * such as 404 or 500.
       *
       * So we explicitly check response.ok.
       */
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      /**
       * Convert the JSON response into a JavaScript object.
       *
       * Example:
       *
       * {
       *   branch: "main",
       *   commits: ["added test", "My First Commit"],
       *   changedFiles: [
       *     " M src/services/git-activity.ts",
       *     "?? vite.config.ts"
       *   ]
       * }
       */
      const gitActivity: GitActivity = await response.json();

      /**
       * Keep the raw Git data for the debug panel,
       * and transform it into Activity[] for the
       * existing <activity-item> list.
       *
       * Because both properties are decorated with
       * @state(), Lit sees these assignments and
       * schedules an update.
       *
       * We do NOT manually call render().
       */
      this.gitActivity = gitActivity;
      this.activity = gitActivityToActivities(gitActivity);
    } catch (error) {
      console.error(error);

      /**
       * Store a user-friendly error message.
       *
       * Updating gitError also causes Lit to update
       * because it is @state().
       */
      this.gitError = 'Could not load Git activity.';
    }
  }

  /**
   * Render the REAL Git activity.
   *
   * We keep this separate from render() so the main
   * template doesn't become difficult to read.
   */
  private renderGitActivity() {
    /**
     * First handle an error.
     *
     * role="alert" lets assistive technology know that
     * an important error message appeared.
     */
    if (this.gitError) {
      return html`
        <p role="alert">
          ${this.gitError}
        </p>
      `;
    }

    /**
     * The fetch is asynchronous.
     *
     * Until it finishes, gitActivity is undefined,
     * so we display a loading message.
     */
    if (!this.gitActivity) {
      return html`
        <p>Loading Git activity...</p>
      `;
    }

    /**
     * Once Git activity exists, render the real data.
     */
    return html`
      <section class="panel git-activity">
        <h2>Local Git Activity</h2>

        <p>
          Branch:
          <strong>${this.gitActivity.branch}</strong>
        </p>

        <h3>Recent commits</h3>

        ${
          this.gitActivity.commits.length
            ? html`
                <ul>
                  ${this.gitActivity.commits.map(
                    (commit) => html`
                      <li>${commit}</li>
                    `,
                  )}
                </ul>
              `
            : html`
                <p>No recent commits.</p>
              `
        }

        <h3>Changed files</h3>

        ${
          this.gitActivity.changedFiles.length
            ? html`
                <ul>
                  ${this.gitActivity.changedFiles.map(
                    (file) => html`
                      <li>${file}</li>
                    `,
                  )}
                </ul>
              `
            : html`
                <p>No uncommitted changes.</p>
              `
        }
      </section>
    `;
  }

  /**
   * Main Lit render method.
   *
   * Lit calls this when the component first renders
   * and whenever one of our reactive properties changes.
   */
  render() {
    return html`
      <main
        class="shell"
        @activity-toggle=${this.onToggle}
      >
        <header>
          <h1>Daily Diff</h1>

          <p class="tagline">
            Your code changed. Your standup should know why.
          </p>
        </header>

        <div class="grid">
          <!-- Activity panel — now powered by real Git data -->
          <section class="panel">
            <h2>Activity</h2>

            <p>
              Human in the loop: choose what the agent may use.
            </p>

            ${
              this.activity.map(
                (activity) => html`
                  <activity-item
                    .activity=${activity}
                  ></activity-item>
                `,
              )
            }

            <button @click=${this.generate}>
              Generate standup
            </button>
          </section>

          <!-- Generated standup -->
          <standup-card
            .standup=${this.standup}
          ></standup-card>
        </div>

        <!--
          NEW:
          Display the real information collected from Git.
        -->
        ${this.renderGitActivity()}
      </main>
    `;
  }

  /**
   * Handles the custom "activity-toggle" event dispatched
   * by an <activity-item>.
   *
   * We don't mutate an Activity directly.
   *
   * Instead, map() creates a new array and the spread
   * operator creates a new object for the changed item.
   *
   * This:
   *
   *   { ...activity, included: e.detail.included }
   *
   * means:
   *
   *   "Copy activity, but replace included with
   *    the new value."
   */
  private onToggle(
    e: CustomEvent<{
      id: string;
      included: boolean;
    }>,
  ) {
    this.activity = this.activity.map((activity) =>
      activity.id === e.detail.id
        ? {
            ...activity,
            included: e.detail.included,
          }
        : activity,
    );
  }

  /**
   * Generate our standup using the activities the user
   * has chosen to include.
   *
   * Right now MockStandupAgent handles this.
   *
   * Later:
   *
   * Activity[]
   *    ↓
   * AI agent
   *    ↓
   * A2UI
   *    ↓
   * Standup UI
   */
  private async generate() {
    this.standup = await this.agent.generate(this.activity);
  }

  /**
   * Component styles.
   */
  static styles = css`
    :host {
      display: block;
      min-height: 100vh;
      background: #f8fafc;
      color: #101828;
      font-family: Inter, system-ui, sans-serif;
    }

    .shell {
      max-width: 1050px;
      margin: auto;
      padding: 3rem 1.25rem;
    }

    header {
      margin-bottom: 2rem;
    }

    h1 {
      margin: 0;
      font-size: 2.4rem;
    }

    h3 {
      padding: 0 1rem;
    }

    .tagline {
      color: #475467;
      font-size: 1.05rem;
    }

    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1.25rem;
    }

    .panel {
      overflow: hidden;
      background: #fff;
      border: 1px solid #d0d5dd;
      border-radius: 14px;
    }

    .panel h2 {
      margin: 0;
      padding: 1rem 1rem 0.4rem;
    }

    .panel p {
      padding: 0 1rem;
      color: #667085;
    }

    .git-activity {
      margin-top: 1.25rem;
      padding-bottom: 1rem;
    }

    .git-activity ul {
      margin: 0 1rem 1rem;
      padding-left: 1.5rem;
    }

    .git-activity li {
      margin-bottom: 0.35rem;
    }

    button {
      margin: 1rem;
      padding: 0.75rem 1rem;
      border: 0;
      border-radius: 9px;
      background: #101828;
      color: white;
      font-weight: 650;
      cursor: pointer;
    }

    /*
     * Don't remove the browser's focus indicator.
     *
     * We're making Daily Diff keyboard accessible
     * from the beginning.
     */
    button:focus-visible {
      outline: 3px solid currentColor;
      outline-offset: 3px;
    }

    @media (max-width: 760px) {
      .grid {
        grid-template-columns: 1fr;
      }
    }
  `;
}